facioquo/stock-indicators-python

- .github/build.main.yml
- setup.py
- Auto-versioning using gitversion.
Fixes #38
> chore: Add auto-versioning

- .github/build.main.yml
- gitversion.yml
> chore: update build

- requirements.txt
- Specify `pythonnet` version.
- will be bumped up soon after compatibility test with version 3.
> chore: Update requirements.txt

- stock_indicators/indicators/adl.py
- stock_indicators/indicators/adx.py
- stock_indicators/indicators/alligator.py
- stock_indicators/indicators/alma.py
- stock_indicators/indicators/aroon.py
- stock_indicators/indicators/atr.py
- stock_indicators/indicators/awesome.py
- stock_indicators/indicators/beta.py
- stock_indicators/indicators/bollinger_bands.py
- stock_indicators/indicators/common/results.py
- stock_indicators/indicators/ema.py
- stock_indicators/indicators/fractal.py
- stock_indicators/indicators/macd.py
- stock_indicators/indicators/rsi.py
- stock_indicators/indicators/sma.py
- stock_indicators/indicators/stoch.py
- stock_indicators/indicators/stoch_rsi.py
- stock_indicators/indicators/super_trend.py
- Add generic to indicator result class to support extending
> feat: Add generic for extending result class

- stock_indicators/indicators/common/results.py
- Fix generic of `find()` helper method.
> fix: Fix `find()` helper method

- .github/workflows/codeql-analysis.yml
Adding CodeQL vulnerability scanning
> add codeQL

- setup.py
- Specify pythonnet version on setup.py
> chore: Specify pythonnet version on setup.py

- tests/test_common.py
- Add test for helper methods
- `find()`
- `remove_warmup_periods(qty)`
> tests: Add tests for helper methods

- docs/README.md
> fix: home page title on doc site

- README.md
- docs/README.md
- docs/_layouts/default.html
- docs/contributing.md
> chore: update docs

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/roc.py
- stock_indicators/indicators/test_roc.py
> feat: Add ROC

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/elder_ray.py
- tests/test_elder_ray.py
> feat: Add Elder-Ray

- stock_indicators/__init__.py
> fix: Remove duplicated import

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/parabolic_sar.py
- tests/test_parabolic_sar.py
> feat: Add parabolic SAR

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/double_ema.py
- tests/test_double_ema.py
> feat: Add Double EMA

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/triple_ema.py
- tests/test_triple_ema.py
> feat: Add Triple EMA

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/donchian.py
- tests/test_donchian.py
- tests/test_elder_ray.py
> feat: Add Donchian channels

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/slope.py
- tests/test_slope.py
> feat: Add Slope

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/ichimoku.py
- tests/test_ichimoku.py
> feat: Add Ichimoku Cloud

- stock_indicators/indicators/ichimoku.py
> refactor: Rename Ichimoku params

- stock_indicators/indicators/heikin_ashi.py
> refactor: Add typing to Heikin Ashi

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/trix.py
- tests/test_trix.py
> feat: Add TRIX

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/stdev_channels.py
- tests/test_stdev_channels.py
- Add Standard Deviation Channels.
> feat: Add Standard Deviation Channels

- stock_indicators/indicators/roc.py
- stock_indicators/indicators/rsi.py
- stock_indicators/indicators/slope.py
- stock_indicators/indicators/sma.py
- Fix wrong output types: SMA, ROC, RSI, Slope
> fix: Fix wrong output types

- stock_indicators/indicators/common/results.py
- Fix wrong typing in results.py
> fix: Fix wrong typing in results.py

- benchmarks/test_benchmark_indicators.py
- Add benchmarks for new indicators.
> tests: Update benchmarks

- stock_indicators/indicators/triple_ema.py
> refactor: Rename TripleEMA to TEMA

- stock_indicators/indicators/double_ema.py
> refactor: Rename DoubleEMA to DEMA

- stock_indicators/__init__.py
- stock_indicators/indicators/adl.py
- stock_indicators/indicators/adx.py
- stock_indicators/indicators/alligator.py
- stock_indicators/indicators/alma.py
- stock_indicators/indicators/aroon.py
- stock_indicators/indicators/atr.py
- stock_indicators/indicators/awesome.py
- stock_indicators/indicators/beta.py
- stock_indicators/indicators/bollinger_bands.py
- stock_indicators/indicators/chandelier.py
- stock_indicators/indicators/donchian.py
- stock_indicators/indicators/double_ema.py
- stock_indicators/indicators/elder_ray.py
- stock_indicators/indicators/ema.py
- stock_indicators/indicators/fractal.py
- stock_indicators/indicators/heikin_ashi.py
- stock_indicators/indicators/ichimoku.py
- stock_indicators/indicators/macd.py
- stock_indicators/indicators/parabolic_sar.py
- stock_indicators/indicators/roc.py
- stock_indicators/indicators/rsi.py
- stock_indicators/indicators/slope.py
- stock_indicators/indicators/sma.py
- stock_indicators/indicators/stdev_channels.py
- stock_indicators/indicators/stoch.py
- stock_indicators/indicators/stoch_rsi.py
- stock_indicators/indicators/super_trend.py
- stock_indicators/indicators/triple_ema.py
- stock_indicators/indicators/trix.py
> style: Fit to pylint

- stock_indicators/indicators/roc.py
> docs: Add docstring to ROCWB

- stock_indicators/_cstypes/datetime.py
- stock_indicators/_cstypes/decimal.py
- stock_indicators/_cstypes/list.py
- Change List, DateTime, Decimal methods to classes.
> refactor: Refactor type conversion method to class

- stock_indicators/indicators/adl.py
- stock_indicators/indicators/adx.py
- stock_indicators/indicators/alligator.py
- stock_indicators/indicators/alma.py
- stock_indicators/indicators/aroon.py
- stock_indicators/indicators/atr.py
- stock_indicators/indicators/awesome.py
- stock_indicators/indicators/beta.py
- stock_indicators/indicators/bollinger_bands.py
- stock_indicators/indicators/chandelier.py
- stock_indicators/indicators/common/helpers.py
- stock_indicators/indicators/donchian.py
- stock_indicators/indicators/double_ema.py
- stock_indicators/indicators/elder_ray.py
- stock_indicators/indicators/ema.py
- stock_indicators/indicators/fractal.py
- stock_indicators/indicators/heikin_ashi.py
- stock_indicators/indicators/ichimoku.py
- stock_indicators/indicators/macd.py
- stock_indicators/indicators/parabolic_sar.py
- stock_indicators/indicators/roc.py
- stock_indicators/indicators/rsi.py
- stock_indicators/indicators/slope.py
- stock_indicators/indicators/sma.py
- stock_indicators/indicators/stdev_channels.py
- stock_indicators/indicators/stoch.py
- stock_indicators/indicators/stoch_rsi.py
- stock_indicators/indicators/super_trend.py
- stock_indicators/indicators/triple_ema.py
- stock_indicators/indicators/trix.py
- Add Mixin classes for helper method for code reusability.
> refactor: Add Mixins for helper methods

- requirements.txt
- stock_indicators/indicators/common/helpers.py
> Fix typing of remove_warmup_periods()

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/keltner.py
- tests/test_keltner.py
> feat: Add Keltner Channels

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/starc_bands.py
- tests/test_starc_bands.py
> feat: Add STARC Bands

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/obv.py
- tests/test_obv.py
> feat: Add On-balance Volume

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/pmo.py
- tests/test_pmo.py
- Add Price Momentum Oscillator.
> feat: Add Price Momentum Oscillator

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/prs.py
- tests/test_prs.py
- Add Price Relative Strength.
> feat: Add Price Relative Strength

- .github/workflows/lock.yml
Updating the GitHub issue/PR lockbot to a newer version and running nightly instead of weekly to help avoid running over usage limits.
> chore: update lockbot

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/smi.py
- tests/test_smi.py
- Add Stochastic Momentum Index.
> feat: Add Stochastic Momentum Index

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/smma.py
- tests/test_smma.py
- Add Smoothed Moving Average.
> feat: Add Smoothed Moving Average

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/stc.py
- tests/test_stc.py
> feat: Add Schaff Trend Cycle

- stock_indicators/indicators/common/helpers.py
- stock_indicators/indicators/common/results.py
- Add docstring to helper methods.
> docs: Add docstring to helper methods

- stock_indicators/_cstypes/datetime.py
- Refactor datetime methods to return None.
> refactor: Refactor datetime functions to return None

- stock_indicators/indicators/common/quote.py
- refactor `from_csquote()` to classmethod for inheritance.
> refactor: refactor `from_csquote()` to classmethod

- stock_indicators/_cslib/__init__.py
- stock_indicators/indicators/beta.py
- stock_indicators/indicators/common/enums.py
- tests/test_beta.py
- Update Beta Coefficient.
Fixes #65
> feat: Update Beta Coefficient

- stock_indicators/indicators/alligator.py
- tests/test_alligator.py
> feat: Update Williams Alligator

- stock_indicators/_cslib/__init__.py
- stock_indicators/indicators/chandelier.py
- stock_indicators/indicators/common/enums.py
- tests/test_chandelier.py
> feat: Update Chandelier Exit

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/pvo.py
- tests/test_pvo.py
- Add Percentage Volume Oscillator
> feat: Add Percentage Volume Oscillator

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/renko.py
- tests/test_renko.py
> feat: Add Renko Chart

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/rolling_pivots.py
- tests/test_rolling_pivots.py
> feat: Add Rolling Pivot Points

- benchmarks/test_benchmark_indicators.py
- stock_indicators/_cstypes/list.py
- Improve performance of converting to C# List.
- Approx. 12% improvement in runnning time.
```bash
------------------------------------------------------ benchmark: 1 tests ------------------------------------------------------
Name (time in ms)                      Min       Max      Mean   StdDev    Median      IQR  Outliers     OPS  Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------
test_benchmark_hurst_longlong     330.1131  426.2715  351.0660  42.0999  332.5940  27.9184       1;1  2.8485       5           1
--------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ …
```
> feat: Improve performance of converting to C# List

- stock_indicators/indicators/common/helpers.py
- stock_indicators/indicators/common/results.py
- Improve performance of creating results.
- Approx. 12~17% improvement in runnning time.
```bash
------------------------------------------------------ benchmark: 1 tests ------------------------------------------------------
Name (time in ms)                      Min       Max      Mean   StdDev    Median      IQR  Outliers     OPS  Rounds  Iterations
--------------------------------------------------------------------------------------------------------------------------------
test_benchmark_hurst_longlong     274.3428  372.7476  294.6430  43.6681  275.1750  25.8243       1;1  3.3939       5           1
--------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------ …
```
> feat: Improve performance of creating results

- stock_indicators/indicators/gator.py
- Fix wrong conditional for `get_gator()`.
> fix: Fix to accept Quote subclass

- setup.py
> chore: Update supported pyversion

- stock_indicators/indicators/sma.py
- tests/test_sma.py
- tests/test_sma_extended.py
-  Support CandlePart for SMA.
> feat: Support CandlePart for SMA

- stock_indicators/indicators/ema.py
- tests/test_ema.py
> feat: Support CandlePart for EMA

- docs/GemFile.lock
- docs/_indicators/DoubleEma.md
- docs/_indicators/TripleEma.md
Fixing broken links due to upstream changes.
Note: see https://github.com/DaveSkender/Stock.Indicators/pull/772 for additional breaking changes for .NET v1.23.0
> chore: fix broken links

- stock_indicators/indicators/common/enums.py
-  Add more CandlePart.
- HL2, OC2, HLC3, OHL3, OHLC4 selection CandlePart options for SMA, EMA, and WMA  - https://github.com/DaveSkender/Stock.Indicators/pull/766
> feat: Add more CandlePart

- stock_indicators/indicators/wma.py
> feat: Support CandlePart for WMA

- .github/build.main.yml
- Update build script to use .NET 2.1.
> chore: Update build script to use .NET 2.1

- stock_indicators/indicators/macd.py
- Support CandlePart for MACD.
> feat: Support CandlePart for MACD 

- docs/README.md
- Fix broken url for [utilities and helper]
> docs: Fix broken url

- .github/workflows/test.yml
- stock_indicators/__init__.py
- stock_indicators/indicators/common/__init__.py
- Add shortcuts for enums.
- Needs corresponding docs updates.
> refactor: Add shortcuts for enums

- setup.py
- Exclude benchmarks from packaging
> chore: Exclude benchmarks from packaging

- .github/build.main.yml
- Add branch V0.8 to trigger workflows.
> chore: Add branch V0.8 to trigger workflows

- tests/test_gator.py
> tests: Fix gator test class name

- gitversion.yml
- Update gitversion.yml.
- experimental...
> chore: Update gitversion.yml

- stock_indicators/indicators/ichimoku.py
- tests/test_ichimoku.py
- Add more params for Ichimoku Cloud
- Add 2 more overloaded methods.
- fixes partially #82
> feat: Add more params for Ichimoku Cloud

- stock_indicators/indicators/parabolic_sar.py
- tests/test_parabolic_sar.py
- Add more params for Parabolic SAR
- Fixes partially #82
> feat: Add more params for Parabolic SAR

- stock_indicators/indicators/beta.py
- stock_indicators/indicators/chandelier.py
- stock_indicators/indicators/common/_contrib/enum.py
- stock_indicators/indicators/common/candles.py
- stock_indicators/indicators/common/enums.py
- stock_indicators/indicators/ema.py
- stock_indicators/indicators/ma_envelopes.py
- stock_indicators/indicators/macd.py
- stock_indicators/indicators/pivot_points.py
- stock_indicators/indicators/pivots.py
- stock_indicators/indicators/renko.py
- stock_indicators/indicators/rolling_pivots.py
- stock_indicators/indicators/sma.py
- stock_indicators/indicators/wma.py
- stock_indicators/indicators/zig_zag.py
- tests/common/test_type_compatibility.py
- Support IntEnum to enable comparison with integer.
Fixes #187
> feat: Support IntEnum

- stock_indicators/indicators/adl.py
- stock_indicators/indicators/chaikin_oscillator.py
- stock_indicators/indicators/cmf.py
- stock_indicators/indicators/trix.py
- Change return types
- ADL
- CMF
- Chaikin Oscillator
- TRIX
> feat: Change return types

- stock_indicators/indicators/rsi.py
- tests/test_rsi.py
> feat: Add alias for RSI value

- stock_indicators/indicators/adx.py
- tests/test_adx.py
> feat: Add adxr return value

- setup.py
- Include runtimeconfig.json into package
> chore: Include runtimeconfig.json into package

- stock_indicators/indicators/sma.py
- Fix docstring of SMA-analysis
> docs: Fix docstring of SMA-analysis

- stock_indicators/indicators/beta.py
- stock_indicators/indicators/prs.py
- Add warnings for param location changed
- PRS, Beta
> feat: Add warnings for param location changed

- stock_indicators/indicators/rsi.py
- tests/test_rsi.py
- Remove unnecessary alias in RSI result
- revert #261
> fix: Remove unnecessary alias

- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/adl.py
- stock_indicators/indicators/common/helpers.py
- stock_indicators/indicators/dema.py
- stock_indicators/indicators/dpo.py
- stock_indicators/indicators/heikin_ashi.py
- stock_indicators/indicators/hurst.py
- stock_indicators/indicators/obv.py
- stock_indicators/indicators/renko.py
- stock_indicators/indicators/rsi.py
- stock_indicators/indicators/tema.py
- Remove deprecated features
- ToQuotesMixin, get_double_ema, get_triple_ema
> feat: Remove deprecated features

- benchmarks/test_benchmark_indicators.py
- docs/_indicators/Beta.md
- docs/_indicators/Prs.md
- stock_indicators/indicators/__init__.py
- stock_indicators/indicators/beta.py
- stock_indicators/indicators/prs.py
- stock_indicators/indicators/sma.py
Removing obsolete warnings from major release breaking changes.
> remove temporary warnings

- tests/test_stdev.py
just some code clean up that i happen to stumble upon
> remove redundant unit test

- .github/workflows/a11y.yml
- .github/workflows/links.yml
- docs/contributing.md
Only run documentation related build or test actions if changed, based on path location.
> path filtering on builds

- .github/workflows/deploy.yml
- Fetch all tags in deploy pipeline
> chore: Fetch all tags in deploy pipeline

- .github/workflows/deploy.yml
- Update to be triggered when tag pushed
> chore: Update to be triggered when tag pushed

- stock_indicators/indicators/ht_trendline.py
- tests/test_ht_trendline.py
- Add Dominant Cycle Periods to HT Trendline
> feat: Add Dominant Cycle Periods to HT Trendline

- stock_indicators/indicators/smi.py
> feat: Add SMI default values

- README.md
- docs/contributing.md
- docs/pages/guide.md
- Add blurb for trouble with converting to quotes
> docs: Add blurb for trouble with converting to quotes

- docs/_indicators/Roc.md
- stock_indicators/indicators/roc.py
- tests/test_roc.py
- Add Momentum to ROC
Fixes #353
> feat: Add Momentum to ROC

- docs/pages/guide.md
Documentation updates only.  No code changes.
> docs: Update guide

- stock_indicators/indicators/stoch.py
- tests/test_stoch.py
- Add optional params on Stochastic Oscillator
> feat: Add optional params on Stochastic Oscillator

- stock_indicators/_cslib/__init__.py
- stock_indicators/indicators/common/results.py
- tests/common/test_indicator_results.py
- Replace find() implementation with Python
> feat: Replace find() implementation with Python

- stock_indicators/_cslib/__init__.py
- stock_indicators/indicators/common/results.py
- Replace remove_warmup_periods() implementation with Python
> feat: Replace remove_warmup_periods() implementation with Python

- docs/GemFile.lock
Maintenance update of doc site gems only.
> chore: Update doc site packages

- .devcontainer/devcontainer.json
This pull request introduces a new development container configuration for a Python project. The configuration includes specifying the container image, terminal settings, necessary extensions, and post-creation commands.
Key changes:
* `.devcontainer/devcontainer.json`: Added a new dev container configuration with the following:
- Container name and image specification.
- Terminal shell setting to use Bash.
- List of VS Code extensions for Python development, including linters and formatters.
- Post-creation command to install project dependencies.
- Workspace folder setting.
- Build and test tasks for the project.Add a dev container configuration for GitHub Copilot compatibility.
* Create `.devcontainer/devcontainer.json` file.
* Configure the dev container with Python 3.9 image.
* Add …
> chore: Container for Copilot Workspace

- .github/workflows/test-indicators.yml
- benchmarks/conftest.py
- stock_indicators/_cslib/__init__.py
- stock_indicators/logging_config.py
- tests/conftest.py
- fixes #416 
- removes extra .NET vs. OS check
- adds check in build for debug settings
> fix: Disable debug logging

- stock_indicators/indicators/common/results.py
> fix: Remove redundant super call
