facioquo/stock-indicators-python

stock_indicators/indicators/adl.py, stock_indicators/indicators/rsi.py
- Fix `to_quotes()` method to return Python object.
=> fix: Fix `to_quotes()` method to return Python object

docs/_config.yml, docs/contributing.md, docs/guide.md, docs/performance.md
- bad URL to performance page in the production site
Side note: I think since the contributor page is a core GitHub page too, we should avoid doing anything that only works in Jekyll site build.  Mostly, this just means hard-coding URLs instead of using `{{ }}` the placeholders.
=> docs: fix bad URLs on contributing page

docs/_indicators/Adx.md
Renamed the source image for ADX since it was being blocked by Ad blockers due to its name.
=> fix: ADX image url

setup.py
- Add typing_extensions to install_requires
=> chore: Add typing_extensions to install_requires in setup.py

requirements.txt, setup.py, stock_indicators/indicators/common/results.py, tests/test_doji.py, tests/test_marubozu.py
- Bump pythonnet from 2.5.2 to 3.0.0a1 .
Fixes #13 , Fixes #58
=> chore: Bump pythonnet from 2.5.2 to 3.0.0a1

stock_indicators/_cslib/__init__.py, stock_indicators/indicators/common/_contrib/type_resolver.py, stock_indicators/indicators/common/candles.py, stock_indicators/indicators/common/quote.py, tests/common/test_type_compatibility.py
- Make inheritance relationship compatible with C#
- CLR does not allow multiple inheritance.
- Wrapper classes are re-assembled when they are inherited.
=> feat: Make inheritance relationship compatible with C#

.github/build.main.yml, setup.py
- Don't let setup.py receive its semver from CLI argument.
- Replace semver in setup.py using `sed`.
prevents #197.
=> chore: Update setup.py for manual build

stock_indicators/indicators/zig_zag.py
- Fix ZigZag `point_type` to be Optional str
=> fix: Fix ZigZag `point_type` to be Optional str

stock_indicators/indicators/common/results.py, tests/common/test_indicator_results.py
- Fix magic methods for built-in list
- `__add__`, `__mul__`
- Add tests for `IndicatorResults` methods
=> fix: Fix magic methods for built-in list

stock_indicators/_cslib/__init__.py
- Drop mono support
- Looks like Mono does not fully support .NET6
=> feat: Drop Mono support

stock_indicators/indicators/common/_contrib/type_resolver.py, stock_indicators/indicators/common/candles.py, stock_indicators/indicators/common/quote.py, tests/common/test_candle.py
- FATAL. It was not able to access candle properties.
- Fix wrapping CandleProperties.
- Add tests for candle properties.
=> fix: Fix wrapping CandleProperties

stock_indicators/_cslib/__init__.py
- Remove clr load handling on x64 darwin
- https://github.com/pythonnet/clr-loader/pull/37 accepted and released.
=> feat: Remove clr load handling on x64 darwin

gitversion.yml
This simply changes feature branch version prefix from `PullRequest` to `preview`, for consistency with the C# library repo.
=> update build label

.github/workflows/semantic-pr-linter.yml
@LeeDongGeon1996 I've noticed you like to use use Conventional Commit standards for PR titles (merge commits).  You've inspired me to add this linter to the Indicator repos.  See https://github.com/DaveSkender/Stock.Indicators/pull/1136 for more information on the implementation.  I didn't add many constraints, kept it fairly flexible.
=> chore: Add PR title linter

.github/workflows/deploy-docs.yml
Renaming the documentation site environment name GitHub Action, to be more descriptive.
=> ci: Rename doc-website environment

benchmarks/test_benchmark_indicators.py, stock_indicators/indicators/starc_bands.py, tests/test_starc_bands.py
- Remove sma_periods default value for StarcBands
=> feat: Remove sma_periods default value for StarcBands

README.md, docs/_indicators/HeikinAshi.md, docs/contributing.md, docs/pages/guide.md, docs/pages/home.md
I disabled Azure DevOps since we’re not using it anymore.
It broke the legacy badge.
=> docs: Remove broken test coverage badge

stock_indicators/_cslib/__init__.py, stock_indicators/_cstypes/decimal.py
- Add explanatory error message for FormatException
=> feat: Add explanatory error message for FormatException

stock_indicators/_cslib/__init__.py, stock_indicators/_cstypes/decimal.py
- Wrap exception for adding exception message
- `add_note()` not supported in Python 3.8
=> fix: Wrap exception to add helpful exception message

stock_indicators/indicators/common/candles.py, stock_indicators/indicators/common/quote.py
- Declare quote wrappers as class for better linting
=> feat: Declare quote wrappers as class for better linting

docs/pages/guide.md
Just some simple naming consistence for _pandas.DataFrame_ and other minor guide updates.
=> docs: Typographical updates to guide

.gitattributes
This adds a basic `.gitattributes` file.  I noticed a git warning:
```bash
LF will be replaced by CRLF the next time Git touches it
```
This should ensure LF line ending consistency, which is generally the standard these days.
=> chore: Add `.gitattributes` file

.github/workflows/test-indicators.yml
Disabling the test-reporter portion of unit tests due to contributor permissions issues; it's always been a bit flaky.
=> ci: Disable test reporter

stock_indicators/indicators/common/results.py, stock_indicators/indicators/gator.py
- Deprecate `reload()` and `done()`
- No memory saving profit
- After removing them, it is guranteed that the type of `_csdata` is always `IEnumerable`(C#).
=> feat: Add deprecation warning on `reload()` and `done()`

benchmarks/test_benchmark_indicators.py
=> test: Update benchmarks

.github/workflows/deploy-website.yml, README.md, docs/GemFile.lock, docs/_config.yml, docs/_headers, docs/_includes/head-style.html, docs/_includes/head.html, docs/_includes/header.html, docs/assets/css/style.scss, docs/pages/home.md
General documentations site updates:
=> docs: Update fonts, styles, CF Pages index exclusion

stock_indicators/_cslib/__init__.py, stock_indicators/_cstypes/datetime.py, stock_indicators/_cstypes/decimal.py, stock_indicators/indicators/common/candles.py, stock_indicators/indicators/vwap.py
- Remove unnecessary validation
- No meaningful performance gain, just for simplification
=> feat: Remove unnecessary validations

stock_indicators/_cstypes/datetime.py, stock_indicators/_cstypes/decimal.py, stock_indicators/indicators/common/quote.py
=> feat: Add type hint on Quote

docs/_indicators/Kama.md
=> docs: Update docs for 1.3.1

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/deploy-website.yml, docs/GemFile.lock
=> ci: Wrangler website deployer

docs/_indicators/Renko.md
=> fix: Renko docs typo

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Fixes #417
Update Issue and PR templates to use new Type markers.
* Replace the `labels` field with the `type` field and set it to "bug" in `.github/ISSUE_TEMPLATE/bug_report.yml`.
* Replace the `labels` field with the `type` field and set it to "feature" in `.github/ISSUE_TEMPLATE/feature_request.yml`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/facioquo/stock-indicators-python/pull/419?shareId=2c4ac296-323e-43d0-9a55-273210e41d0b).
=> chore: Update issue templates with new Types

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/lint-pull-request.yml, .github/workflows/test-indicators.yml
This pull request includes changes to the GitHub workflows to update the pull request event and testing environments. The most important changes include modifying the event type for pull request workflows and updating the operating system versions in the test matrix.
Updates to GitHub workflows:
* [`.github/workflows/lint-pull-request.yml`](diffhunk://#diff-c5b6848e526582281ad38f6c3a746c12470230d63ae6b3586bf9261741f5d5ceL4-R4): Changed the event type from `pull_request` to `pull_request_target` to ensure the workflow runs with the correct permissions.
* [`.github/workflows/test-indicators.yml`](diffhunk://#diff-1e6ce7fdb17acdc0416421b7fe6b63ebec67f618f44b8b9a911dc14e81ec2e09L19-R19): Updated the operating system versions in the test matrix to include `ubuntu-24.04-arm` instead of …
=> ci: Fix PR title linter, add ARM64 runner

.github/workflows/test-code-coverage.yml, .github/workflows/test-indicators.yml
This pull request includes several updates to the GitHub Actions workflows to improve test code coverage and indicators. The changes involve modifying the workflow triggers, adding concurrency limits, updating environment variables, and refining the job matrix configurations.
Key changes include:
* [`.github/workflows/test-code-coverage.yml`](diffhunk://#diff-a56235f489cdc191f584a3562a2725698debc96ce17ee6e89ed6d4e3ac99c4dcL9-R17): Changed the trigger from `pull_request` to `pull_request_target` and added concurrency limits to prevent multiple runs from overlapping.
* [`.github/workflows/test-code-coverage.yml`](diffhunk://#diff-a56235f489cdc191f584a3562a2725698debc96ce17ee6e89ed6d4e3ac99c4dcR26-R34): Added the `CODACY_PROJECT_TOKEN` environment variable and updated the checkout step to …
=> ci: Update workflows

benchmarks/conftest.py, benchmarks/test_benchmark_indicators.py
Add performance tests for CsObject conversion
=> test: Add performance tests for CsObject conversion
